apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30003  # Change this if you want a different port
